server:
  port: 9000
spring:
  application:
    name: xdclass-video-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Kehong0028..
    url: jdbc:mysql://42.194.140.230:3306/xd_cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.39.100:8848
mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl